# Generated by Django 5.1.7 on 2025-06-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('author', models.CharField(max_length=10)),
            ],
        ),
    ]
